In [1]:
import numpy as np
import gym
import gym_draughts
import pygame
from draught_surf import DraughtVisualiser, find_square

pygame 2.0.1 (SDL 2.0.14, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
import numpy as np
import gym
import gym_draughts
import pygame
from draught_surf import DraughtVisualiser, find_square

class PvPEngine:
    def __init__(self):

        """
        Class for human v human play with visualiser. Simply load the class
        and run .run()
        """
        self.env = gym.make('draughts-v0')

    def run(self):
        pygame.init()
        d_surf = pygame.display.set_mode((800,800))
        vis = DraughtVisualiser(800,6)
        vis.draw_board()
        d_surf.blit(vis.my_surf, (0,0))
        pygame.display.set_caption("Test!")
        vis.draw_from_grid(self.env.board.board)
        pygame.display.update()
        MOVETHISPIECE = 0
        last_click = None

        while True: # main game loop
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                if event.type == pygame.MOUSEBUTTONUP:

                    pos = pygame.mouse.get_pos()
                    square = find_square( (0,0), pos, 800/6)
                    MOVETHISPIECE = square
                    last_click = square

                if event.type==pygame.KEYDOWN:
                    key_name=pygame.key.name(event.key)
                    if key_name=='w':
                        self.env.step([MOVETHISPIECE[0], MOVETHISPIECE[1], 0])
                        last_click = None
                    if key_name=='e':
                        self.env.step([MOVETHISPIECE[0], MOVETHISPIECE[1], 3])
                        last_click = None
                    if key_name=='d':
                        self.env.step([MOVETHISPIECE[0], MOVETHISPIECE[1], 2])
                        last_click = None
                    if key_name=='s':
                        self.env.step([MOVETHISPIECE[0], MOVETHISPIECE[1], 1])
                        last_click = None

            vis.draw_from_grid(self.env.board.board)
            vis.draw_click_marker(last_click)
            colour=pygame.Color("chocolate1")
            d_surf.blit(vis.my_surf, (0,0))
            pygame.display.update()

In [3]:
game = PvPEngine()
game.run()

SQUARE: 1 5
move inputs (array([[ 1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0., -1.,  0., -1.,  0.],
       [ 0., -1.,  0., -1.,  0., -1.]]), array([1, 5]), 3, -1)
SQUARE: 4 4
move inputs (array([[ 1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0., -1.,  0., -1.,  0.],
       [ 0., -1.,  0., -1.,  0., -1.]]), array([4, 4]), 0, -1)
SQUARE: 1 5
move inputs (array([[ 1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  0.],
       [-1.,  0., -1.,  0.,  0.,  0.],
       [ 0., -1.,  0., -1.,  0., -1.]]), array([1, 5]), 3, 1)
SQUARE: 3 3
move inputs (array([[ 1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0

error: display Surface quit

In [22]:
board = gym.make('draughts-v0')

In [23]:
board.render()

[[ 1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [-1.  0. -1.  0. -1.  0.]
 [ 0. -1.  0. -1.  0. -1.]]


In [26]:
board.step([4,0,1])

(array([[ 1.,  0.,  1.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  1.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0., -1.,  0.,  0.,  0.,  0.],
        [ 0.,  0., -1.,  0., -1.,  0.],
        [ 0., -1.,  0., -1.,  0., -1.]]),
 0.3,
 False,
 False)

In [28]:
board.step([1,1,3])

(array([[ 1.,  0.,  1.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  1.],
        [ 1.,  0.,  0.,  0.,  0.,  0.],
        [ 0., -1.,  0.,  0.,  0.,  0.],
        [ 0.,  0., -1.,  0., -1.,  0.],
        [ 0., -1.,  0., -1.,  0., -1.]]),
 0.3,
 False,
 False)