In [1]:
import numpy as np
import gym
import gym_draughts
import pygame
from display.draught_surf import DraughtVisualiser, find_square

pygame 2.0.1 (SDL 2.0.14, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
def move_to_index(move, max_height):
    # Assume move is (x,y,dir). xs are merged together because diagonals
    x_contribution = move[0]//2 * max_height * 4
    y_contribution = move[1] * 4
    return x_contribution + y_contribution + move[2]

def index_to_move(index, max_height, top_left = True):
    direction = index % 4
    y_move = (index//4) % (max_height)
    x_move = (index // (4 * max_height)) * 2 # Times 2 is for collapsing.
    x_adjustment = (y_move + top_left + 1) % 2
    x_move += x_adjustment
    return (x_move, y_move, direction)

In [3]:
index_to_move(move_to_index([4,0,1], 6), 6)

(4, 0, 1)

In [4]:
env = gym.make('draughtsrandom-v0')

In [5]:
env.render()

[[ 1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [-1.  0. -1.  0. -1.  0.]
 [ 0. -1.  0. -1.  0. -1.]]


In [6]:
env.step(move_to_index([4,0,1], 6))[-1]

1
6


False

In [7]:
env.render()

[[ 1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.]
 [ 0.  0. -1.  0. -1.  0.]
 [ 0. -1.  0. -1.  0. -1.]]


In [8]:
env.step(move_to_index([3,1,0], 6))[-1]

1
34


False

In [9]:
env.render()

[[ 1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  1.]
 [-1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0. -3.  0. -3.  0.]
 [ 0. -1.  0. -1.  0. -1.]]
